name = "secure-content-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "CONTENT_KV"
id = "4b104333dad84a08acdb9c3ee5f30642"

[vars]
# ADMIN_PASSWORD should be set in Cloudflare Dashboard
# Do not commit real password to git
